In [1]:
import torch

In [2]:
a = torch.randn(2, 2)


In [3]:
a


tensor([[ 0.7162,  0.2950],
        [-1.4498,  0.0110]])

In [4]:
a = ((a * 3) / (a - 1))#逐元素乘

In [5]:
a

tensor([[-7.5691, -1.2554],
        [ 1.7754, -0.0333]])

In [6]:
0.7162*3/(0.7162-1)

-7.570824524312895

In [9]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [15]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [16]:
y = x + 2
z = y * y * 3
out = z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [17]:
out.backward()

In [18]:
print(x.grad)#=d（out）/ dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [27]:
#from torch.autograd.functional import hessian
def pow_reducer(x):
    return x.pow(3).sum()
inputs = torch.rand(2, 2)
hessian(pow_reducer, inputs)

NameError: name 'hessian' is not defined

In [26]:
import torch.autograd

In [3]:
print(torch.cuda.is_available())

True
